name: Build Geode Mod

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64

      - name: Upload .geode file
        uses: actions/upload-artifact@v4
        with:
          name: fps-unlocker-geode
          path: ${{ steps.build.outputs.build-output }}
